from src.CNNClassifier.components.data_ingestion import DataIngestion
from src.CNNClassifier.components.prepare_base_model import PrepareBaseModel
from src.CNNClassifier.components.callbacks import Callbacks