# here we write configuration settings
artifacts_root: artifacts
model_root: model

#data ingestion configuration settings(like path, data_source_url,data_split_path etc)
data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: https://github.com/Mahadevkharmate/Datasets/raw/refs/heads/main/cat-dog-data.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

#prepare base model
prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/base_model.h5
  updated_base_model_path: artifacts/prepare_base_model/base_model_updated.h5


#preparing callbacks config
callbacks:
  root_dir : artifacts/callbacks
  tensorboard_root_log_dir: artifacts/callbacks/tensorboard_root_log_dir
  checkpoint_model_filepath: artifacts/callbacks/checkpoint_dir/model.h5


#preapring model training configs
training:
  root_dir: artifacts/training
  trained_model_path: artifacts/training/model.h5
